import {
  ARTIST_COLUMN,
  ASCENDING,
  DESCENDING,
  DURATION_COLUMN,
  NAME_COLUMN,
} from "framework-compare-types";

export { ARTIST_COLUMN, ASCENDING, DESCENDING, DURATION_COLUMN, NAME_COLUMN };
