// GENERATED BY MITOSIS

import { Fragment, component$, h } from "@builder.io/qwik";
type LoginLinkProps = {
  href: string;
};
export const LoginLink = component$((props: LoginLinkProps) => {
  return (
    <a
      class="block w-full rounded-full border border-solid border-white p-2 text-center text-white"
      {...props}
    >
      Login
    </a>
  );
});
export default LoginLink;
