// GENERATED BY MITOSIS

import DownArrow from "./DownArrow";
import UpArrow from "./UpArrow";
import { Fragment, Slot, component$, h } from "@builder.io/qwik";
import { ASCENDING, SortDirection } from "framework-compare-types";
type TableHeaderButtonProps = {
  children: any;
  sorted: boolean;
  ascending: boolean;
} & HTMLButtonElement;
export const TableHeaderButton = component$((props: TableHeaderButtonProps) => {
  return (
    <button {...props}>
      <Slot></Slot>
      {props.sorted ? (
        <div>{props.ascending ? <UpArrow></UpArrow> : <DownArrow></DownArrow>}</div>
      ) : null}
    </button>
  );
});
export default TableHeaderButton;
