// GENERATED BY MITOSIS

import { Fragment, component$, h } from "@builder.io/qwik";
export const TrackTableHeaderAlbumImage = component$((props: any) => {
  return (
    <th class="absolute max-w-0 overflow-hidden left-[-99999px]">
      Album Image
    </th>
  );
});
export default TrackTableHeaderAlbumImage;
