// GENERATED BY MITOSIS

import { Fragment, Slot, component$, h } from "@builder.io/qwik";
type TrackTableHeaderDurationProps = {
  children: any;
};
export const TrackTableHeaderDuration = component$(
  (props: TrackTableHeaderDurationProps) => {
    return (
      <th class="text-xl font-normal py-2 px-2 pr-6">
        <Slot></Slot>
      </th>
    );
  }
);
export default TrackTableHeaderDuration;
