// GENERATED BY MITOSIS

import { Fragment, Slot, component$, h } from "@builder.io/qwik";
type TrackTableHeaderArtistProps = {
  children: any;
};
export const TrackTableHeaderArtist = component$(
  (props: TrackTableHeaderArtistProps) => {
    return (
      <th class="text-xl font-normal py-2 px-2 text-start">
        <Slot></Slot>
      </th>
    );
  }
);
export default TrackTableHeaderArtist;
