// GENERATED BY MITOSIS

import { Fragment, Slot, component$, h } from "@builder.io/qwik";
type TrackTableProps = {
  children: any;
};
export const TrackTable = component$((props: TrackTableProps) => {
  return (
    <div class="border border-[#f4f4f444] rounded-lg">
      <table class="table-auto w-full">
        <Slot></Slot>
      </table>
    </div>
  );
});
export default TrackTable;
