// GENERATED BY MITOSIS

import { Fragment, Slot, component$, h } from "@builder.io/qwik";
type TrackTableHeaderTitleProps = {
  children: any;
};
export const TrackTableHeaderTitle = component$(
  (props: TrackTableHeaderTitleProps) => {
    return (
      <th class="text-xl font-normal py-2 px-2 text-start">
        <Slot></Slot>
      </th>
    );
  }
);
export default TrackTableHeaderTitle;
