// GENERATED BY MITOSIS

import { component$, Slot } from "@builder.io/qwik";

export const PageWrapper = component$(() => {
  return (
    <div class="min-h-screen bg-gradient-to-br from-slate to-darkPurple text-white min-h-screen\tw-full px-6 py-8">
      <Slot></Slot>
    </div>
  );
});
export default PageWrapper;
