// GENERATED BY MITOSIS

import { Slot, component$ } from "@builder.io/qwik";

export const PlaylistList = component$(() => {
  return (
    <ul class="flex flex-col gap-8">
      <Slot></Slot>
    </ul>
  );
});
export default PlaylistList;
