// GENERATED BY MITOSIS

import { component$, Slot } from "@builder.io/qwik";
type PlaylistListItemProps = {
  key: string;
};
export const PlaylistListItem = component$((props: PlaylistListItemProps) => {
  return (
    <li {...props}>
      <Slot></Slot>
    </li>
  );
});
export default PlaylistListItem;
