// GENERATED BY MITOSIS

import { Slot, component$ } from "@builder.io/qwik";

export const TrackTableHeaderDuration = component$(() => {
  return (
    <th class="text-xl font-normal py-2 px-2 pr-6">
      <Slot></Slot>
    </th>
  );
});
export default TrackTableHeaderDuration;
