// GENERATED BY MITOSIS

import { component$ } from "@builder.io/qwik";
export const TrackTableHeaderAlbumImage = component$(() => {
  return <th class="absolute max-w-0 overflow-hidden left-[-99999px]">Album Image</th>;
});
export default TrackTableHeaderAlbumImage;
