// GENERATED BY MITOSIS

import { Slot, component$ } from "@builder.io/qwik";

export const TrackTable = component$(() => {
  return (
    <div class="border border-[#f4f4f444] rounded-lg">
      <table class="table-auto w-full">
        <Slot></Slot>
      </table>
    </div>
  );
});
export default TrackTable;
