// GENERATED BY MITOSIS

import { component$, Slot } from "@builder.io/qwik";

export const TrackTableHeaderArtist = component$(() => {
  return (
    <th class="text-xl font-normal py-2 px-2 text-start">
      <Slot></Slot>
    </th>
  );
});
export default TrackTableHeaderArtist;
